[package]
name = "octabot"
version = "0.1.0"
authors = ["Roman Efremenko <roman.efremenko@gmail.com>"]
publish = false
license = "MIT"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.95"
async-trait = "0.1.84"
chrono = { version = "0.4.39", features = ["serde"] }
dotenvy = "0.15.7"
openssl-sys = { version = "0.9", features = ["vendored"] }
sqlx = { version = "0.8.2", features = [
  "sqlite",
  "runtime-tokio",
  "tls-native-tls",
  "chrono",
  "uuid",
] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["full"] }
tokio-util = "0.7.13"
tracing = { version = "0.1.41", features = ["attributes"] }
tracing-subscriber = { version = "0.3.19", features = [
  "registry",
  "env-filter",
] }
uuid = { version = "1.11.0", features = ["serde", "v4"] }

[dependencies]
anyhow = { workspace = true }
dotenvy = { workspace = true }
futures = "0.3.31"
sqlx = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
octabot-api = { path = "crates/api" }
octabot-plugins = { path = "crates/plugins" }

[workspace]
resolver = "2"
members = ["crates/*"]

# default to small, optimized workspace release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
strip = true
